remote_theme: pages-themes/cayman@v0.2.0
description: "Satelite workshop of ICALP 2025, July 7th 2025, Aarhus"
show_downloads: false

github:
  is_project_page: false

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have on

steps:
  - title: CFP
    description: Generate a GitHub Pages site with the automatic page generator.
    body: cfp/index.md
    link: 'https://taap25.github.io/cfp'
